language: node_js
node_js:
  - "0.10"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g grunt-cli
  - npm install -g karma
  - npm install -g bower
  - bower install

notifications:
  email:
    - chris.burrell@rackspace.com
    - eddy.hernandez@rackspace.com

script:
  - grunt
